apiVersion: apps/v1
kind: Deployment
metadata:
  name: immudb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immudb-deployment
  template:
    metadata:
      labels:
        app: immudb-deployment
    spec:
      containers:
      - name: immudb-pod
        image: codenotary/immudb:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
